#!/usr/bin/env python3
"""Generate db/seed.sql for RoadRescue sample data.

Produces:
  - 1 admin + 15 customer accounts (APP_USER)
  - 12 shop-owner accounts (SHOP)
  - 22 service requests across all statuses

Passwords are hashed with BCrypt using the $2a$ prefix, because
RoadRescueApplication's startup runner only treats $2a$ as "already hashed".
"""
import bcrypt
import datetime
import json
import os

def h(pw: str) -> str:
    return bcrypt.hashpw(pw.encode(), bcrypt.gensalt(prefix=b"2a", rounds=10)).decode()

def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace("'", "''")

ADMIN_PW = "admin123"
CUST_PW = "customer123"
SHOP_PW = "shop123"

lines = []
lines.append("-- RoadRescue sample data")
lines.append("-- Generated by db/generate_seed.py")
lines.append("-- Login: admin/admin123, customer01..15/customer123, shop01..12/shop123")
lines.append("")
lines.append("SET FOREIGN_KEY_CHECKS = 0;")
lines.append("DELETE FROM service_request;")
lines.append("DELETE FROM shop;")
lines.append("DELETE FROM app_user WHERE role = 'CUSTOMER';")
lines.append("SET FOREIGN_KEY_CHECKS = 1;")
lines.append("")

# ---------------- Users ----------------
lines.append("-- ===== USERS: admin (if missing) + 15 customers =====")
admin_hash = h(ADMIN_PW)
lines.append(
    "INSERT INTO app_user (username, password, role) "
    "SELECT 'admin', '{0}', 'ADMIN' FROM DUAL "
    "WHERE NOT EXISTS (SELECT 1 FROM app_user WHERE username = 'admin');".format(admin_hash)
)

customers = []
for i in range(1, 16):
    uname = "customer%02d" % i
    customers.append(uname)
    lines.append(
        "INSERT INTO app_user (username, password, role) VALUES "
        "('{0}', '{1}', 'CUSTOMER');".format(uname, h(CUST_PW))
    )
lines.append("")

# ---------------- Shops ----------------
lines.append("-- ===== SHOPS (12) =====")
# name, owner, email, phone, area, lat, lng, open, close
shop_defs = [
    ("Shree Auto Works",     "Ramesh Patil",    "shop01@roadrescue.local", "9820011001", "Shivajinagar",   18.5308, 73.8478, "00:00", "23:59"),
    ("Highway Motors",       "Sunil Deshmukh",  "shop02@roadrescue.local", "9820011002", "Wakad",          18.5989, 73.7620, "00:00", "23:59"),
    ("SpeedFix Garage",      "Imran Shaikh",    "shop03@roadrescue.local", "9820011003", "Kothrud",        18.5074, 73.8077, "00:00", "23:59"),
    ("Auto Care Center",     "Vijay More",      "shop04@roadrescue.local", "9820011004", "Hadapsar",       18.5089, 73.9260, "00:00", "23:59"),
    ("RoadStar Mechanics",   "Anil Jadhav",     "shop05@roadrescue.local", "9820011005", "Baner",          18.5642, 73.7769, "00:00", "23:59"),
    ("PitStop Auto Repairs", "Sachin Kulkarni", "shop06@roadrescue.local", "9820011006", "Katraj",         18.4529, 73.8567, "00:00", "23:59"),
    ("Highway Rescue Point", "Farhan Khan",     "shop07@roadrescue.local", "9820011007", "Chinchwad",      18.6279, 73.8009, "00:00", "23:59"),
    ("Premier Auto Service", "Ganesh Shinde",   "shop08@roadrescue.local", "9820011008", "Aundh",          18.5586, 73.8075, "00:00", "23:59"),
    ("City Wheel Care",      "Rahul Gaikwad",   "shop09@roadrescue.local", "9820011009", "Viman Nagar",    18.5670, 73.9143, "00:00", "23:59"),
    ("Trust Motors",         "Amit Pawar",      "shop10@roadrescue.local", "9820011010", "Magarpatta",     18.5158, 73.9272, "00:00", "23:59"),
    ("Express Breakdown Co", "Nilesh Sawant",   "shop11@roadrescue.local", "9820011011", "Pimpri",         18.6298, 73.7997, "00:00", "23:59"),
    ("Roadside Heroes",      "Suresh Chavan",   "shop12@roadrescue.local", "9820011012", "Nigdi",          18.6500, 73.7700, "00:00", "23:59"),
]

for idx, (name, owner, email, phone, area, lat, lng, op, cl) in enumerate(shop_defs, start=1):
    uname = "shop%02d" % idx
    branches = [
        {"name": name + " - Main", "address": area + ", Pune", "lat": lat, "lng": lng},
        {"name": name + " - Branch", "address": area + " Extn, Pune", "lat": round(lat + 0.01, 4), "lng": round(lng + 0.01, 4)},
    ]
    bj = esc(json.dumps(branches))
    lines.append(
        "INSERT INTO shop (id, username, password, role, shop_name, owner_name, email, phone, "
        "opening_time, closing_time, branches_json) VALUES "
        "({0}, '{1}', '{2}', 'SHOP_OWNER', '{3}', '{4}', '{5}', '{6}', '{7}', '{8}', '{9}');".format(
            idx, uname, h(SHOP_PW), esc(name), esc(owner), email, phone, op, cl, bj
        )
    )
lines.append("")

# ---------------- Service requests ----------------
lines.append("-- ===== SERVICE REQUESTS (22) =====")
issues = [
    "Flat Tyre", "Battery Dead", "Out of Fuel", "Engine Overheat",
    "Brake Failure", "Car Not Starting", "Headlight Not Working",
    "Radiator Leak", "Clutch Problem", "Key Locked Inside",
    "Towing Required", "Alternator Issue", "Suspension Noise",
    "Steering Vibration", "Oil Leak", "Windshield Crack",
    "Battery Jump Start", "Puncture", "Accelerator Stuck", "Coolant Leak",
    "Spark Plug Issue", "Flat Battery Replacement",
]
mechanics = [
    ("Ravi Kumar", "9988001001", "15 mins"),
    ("Deepak Yadav", "9988001002", "25 mins"),
    ("Sandeep Rao", "9988001003", "10 mins"),
    ("Manoj Verma", "9988001004", "20 mins"),
    ("Arjun Nair", "9988001005", "30 mins"),
    ("Kiran Joshi", "9988001006", "12 mins"),
    ("Sagar Pawar", "9988001007", "18 mins"),
    ("Vikas Singh", "9988001008", "22 mins"),
]
# base points near the shops
points = [
    (18.5204, 73.8567), (18.5310, 73.8448), (18.5600, 73.7900),
    (18.5100, 73.9200), (18.6000, 73.7600), (18.4700, 73.8500),
    (18.6300, 73.8000), (18.5500, 73.8100), (18.5700, 73.9100),
    (18.6200, 73.9000),
]
# statuses: Pending(ASSIGNED), Pending(BROADCAST), Accepted, Completed(+review)
plan = [
    # (status, stage, shop_id, has_mechanic, rating, comment)
    ("Pending",   "ASSIGNED",  1, False, None, None),
    ("Pending",   "ASSIGNED",  2, False, None, None),
    ("Pending",   "BROADCAST", None, False, None, None),
    ("Pending",   "OPEN",      None, False, None, None),
    ("Accepted",  "ASSIGNED",  3, True,  None, None),
    ("Accepted",  "ASSIGNED",  4, True,  None, None),
    ("Accepted",  "ASSIGNED",  5, True,  None, None),
    ("Accepted",  "ASSIGNED",  6, True,  None, None),
    ("Completed", "ASSIGNED",  7, True,  5, "Quick and professional. Reached in 15 minutes."),
    ("Completed", "ASSIGNED",  8, True,  4, "Good service, reasonable price."),
    ("Completed", "ASSIGNED",  9, True,  5, "Excellent roadside help. Highly recommended."),
    ("Completed", "ASSIGNED", 10, True,  3, "Took a while but fixed the issue."),
    ("Completed", "ASSIGNED", 11, True,  5, "Very helpful mechanics."),
    ("Completed", "ASSIGNED", 12, True,  4, "Prompt response, fair pricing."),
    ("Completed", "ASSIGNED",  1, True,  None, None),
    ("Completed", "ASSIGNED",  2, True,  5, "Saved my trip. Thank you!"),
    ("Pending",   "ASSIGNED",  3, False, None, None),
    ("Pending",   "BROADCAST", None, False, None, None),
    ("Accepted",  "ASSIGNED",  4, True,  None, None),
    ("Completed", "ASSIGNED",  5, True,  4, "Reliable service."),
    ("Pending",   "ASSIGNED",  6, False, None, None),
    ("Completed", "ASSIGNED",  7, True,  5, "Best experience so far."),
]

now = datetime.datetime.now()
for i, row in enumerate(plan):
    status, stage, shop_id, has_mech, rating, comment = row
    cust = customers[i % len(customers)]
    issue = issues[i % len(issues)]
    lat, lng = points[i % len(points)]
    lat = round(lat + (i % 5) * 0.002, 6)
    lng = round(lng + (i % 3) * 0.002, 6)
    created = now - datetime.timedelta(days=(i % 14), hours=(i % 7) + 1)
    created_s = created.strftime("%Y-%m-%d %H:%M:%S")
    last_s = created_s
    phone = "98%08d" % (70000000 + i)
    vehicle = "MH %02d %s %04d" % ((i % 30) + 1, chr(65 + (i % 26)) + chr(65 + ((i + 3) % 26)), 1000 + i)

    mech_name = mech_phone = mech_eta = "NULL"
    mech_lat = mech_lng = "NULL"
    if has_mech:
        mn, mp, me = mechanics[i % len(mechanics)]
        mech_name = "'" + mn + "'"
        mech_phone = "'" + mp + "'"
        mech_eta = "'" + me + "'"
        mech_lat = str(round(lat + 0.003, 6))
        mech_lng = str(round(lng + 0.003, 6))

    rating_s = "NULL" if rating is None else str(rating)
    comment_s = "NULL" if comment is None else "'" + esc(comment) + "'"
    shop_s = "NULL" if shop_id is None else str(shop_id)
    assigned = shop_s
    admin_notified = 1 if stage == "OPEN" else 0
    rejected = "''" if stage != "BROADCAST" else "'" + ",".join(["1", "2"]) + "'"

    lines.append(
        "INSERT INTO service_request (customer_name, phone, vehicle_number, issue, status, created_at, "
        "latitude, longitude, mechanic_name, mechanic_phone, mechanic_eta, mechanic_latitude, mechanic_longitude, "
        "review_rating, review_comment, assigned_shop_id, rejected_shop_ids, assignment_stage, last_assigned_at, admin_notified) VALUES "
        "('{cust}', '{phone}', '{veh}', '{issue}', '{status}', '{created}', {lat}, {lng}, "
        "{mn}, {mp}, {me}, {mlat}, {mlng}, {rating}, {comment}, {shop}, {rej}, '{stage}', '{last}', {admin});".format(
            cust=cust, phone=phone, veh=esc(vehicle), issue=esc(issue), status=status, created=created_s,
            lat=lat, lng=lng, mn=mech_name, mp=mech_phone, me=mech_eta, mlat=mech_lat, mlng=mech_lng,
            rating=rating_s, comment=comment_s, shop=assigned, rej=rejected, stage=stage, last=last_s,
            admin=admin_notified,
        )
    )

lines.append("")
lines.append("-- Done.")

out_dir = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(out_dir, "seed.sql"), "w") as f:
    f.write("\n".join(lines) + "\n")

# Also emit to the classpath so the app can seed itself on first boot
resource_dir = os.path.join(out_dir, "..", "src", "main", "resources", "db")
os.makedirs(resource_dir, exist_ok=True)
with open(os.path.join(resource_dir, "seed.sql"), "w") as f:
    f.write("\n".join(lines) + "\n")

print("Wrote", os.path.join(out_dir, "seed.sql"))
print("Wrote", os.path.join(resource_dir, "seed.sql"))
print("customers:", len(customers), "shops:", len(shop_defs), "requests:", len(plan))
